### ISSUE TITLE
Persist Balances Between Sessions

### ISSUE THREAD

**Issue by jettblu** [KryptikApp/kryptikwebapp#6]
#### Description
Balances do not persist between user sessions. This results in a 15-20 second period where a user must wait for balances to load. The delay is managed by a loading bar and skeleton screen, but it would be helpful for old balances to show, while new balances are being fetched at the initiation of a new session. 

#### Tasks
- [ ] Add a **balance encryption** method. Balances are private and should be encrypted before storage. 
- [ ] Add a **long-term storage** method. This method should take a fresh balance object and persist it in long-term storage (consider IndexDb).
- [ ] Add a **retrieval** function. This method will be called at the beginning of a new session and should return balances from long-term storage.

**Comment by jettblu** [comment]
The initial load of balances may also be accelerated by transforming sequential requests into parallel requests, each with their own callback method.

**Comment by jettblu** [comment]
Parallel requests and a simple cache work well, boosting fetch time by over 10x.
